@startuml
autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Bob -> Daniel: Hey
Daniel --> Bob: OK

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml